/* eslint-disable */
// This file is normally generated by TanStack Router's file-based routing tooling.
// It's checked in so `npx tsc --noEmit` works even if the generator hasn't run.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as ProjectsRoute } from "./routes/projects";
import { Route as ProjectRoute } from "./routes/projects.$projectId";
import { Route as ReviewRoute } from "./routes/review";
import { Route as EntityRoute } from "./routes/entities.$entityId";
import { Route as SettingsRoute } from "./routes/settings";

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProjectsRoute,
  ProjectRoute,
  ReviewRoute,
  EntityRoute,
  SettingsRoute,
]);

